# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Liang FANG’s Blog
tagline:             My Thoughts On Everything
description:         Senior Analyst @ Baidu, HUSTer, Father, Wuhan → Beijing, love Podcast, Typography, MOOC, and Table Tennis.
url:                 
baseurl:             ''
paginate:            5
plugins: [jekyll-paginate]

# About/contact
author:
  name:              Liang FANG
  url:               https://twitter.com/fangfrancis
  email:             fangfrancis@gmail.com


